### ISSUE TITLE
Examples use Old Control Schema

### ISSUE THREAD

**Issue by ProbablePrime** [WatchBeam/beam-interactive-java#6]
The examples uses methods like `hasDown` and `getCode` which no longer exist.

It would be awesome for potential developers to get them updated.

**Comment by MattJustMatt** [comment]
Working on this next week!

**Comment by ttaylorr** [comment]
Sorry, I wrote some code to fix this, but forgot to push until just now. The WiFi at school doesn't allow me to push over SSH, and setting up my 2fa credentials is a pain. Pushing now 😄

**Comment by ProbablePrime** [comment]
Closing, Taylor sorted it :)
